# Generated by Django 5.0.4 on 2024-04-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='details',
            new_name='detalles',
        ),
        migrations.RenameField(
            model_name='tareas',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='tareas',
            old_name='title',
            new_name='titulo',
        ),
    ]
